CREATE TABLE players(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(64),balance DECIMAL(12,2) DEFAULT 1000.00);
CREATE TABLE hands(id BIGINT AUTO_INCREMENT PRIMARY KEY,player_id INT,bet DECIMAL(12,2),cards VARCHAR(16),result VARCHAR(16),payout DECIMAL(12,2),played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(player_id) REFERENCES players(id));
